name: Java CI with Gradle
on:
  push:
    branches: [ main ]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute privilege to gradlew
      run: chmod +x gradlew || exit 42
    - name: Test with gradle
      run: ./gradlew test || exit 43

