name: Java CI with Gradle
on:
  push:
    branches: [ main ]
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: PRKL
      run: /bin/false
    #- name: Grant execute permission for gradlew
    #  run: /usr/bin/chmod a+x gradlew
    - name: Test with Gradle
      run: ./gradlew test
